name: CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  release:
    types:
      - published

  workflow_dispatch:
    inputs:
      deploy:
        type: boolean
        description: 'Deploy theme'
        default: false
        required: true

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build theme
        run: yarn lint

  check:
    name: Shopify Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Theme Check
        uses: shopify/theme-check-action@v1

  deploy:
    if: github.event.inputs.deploy == 'true' || github.event_name == 'release'
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - lint
      - check

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build theme
        run: yarn build

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: shopify
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: Automated theme deploy ({sha})
